import requests

from backend.config import get_settings
from backend.schemas.incident import IncidentReport


PRIORITY_LABEL = {
    "P1": "priority:critical",
    "P2": "priority:high",
    "P3": "priority:medium",
    "P4": "priority:low",
}

LABEL_COLOURS = {
    "priority:critical": "d73a4a",
    "priority:high": "e4e669",
    "priority:medium": "0075ca",
    "priority:low": "cfd3d7",
    "csirt-autopilot": "5319e7",
}


def _ensure_labels(repo: str, headers: dict) -> None:
    existing_response = requests.get(
        f"https://api.github.com/repos/{repo}/labels",
        headers=headers,
        timeout=5,
    )
    existing_labels = (
        {label["name"] for label in existing_response.json()}
        if existing_response.ok
        else set()
    )

    for name, colour in LABEL_COLOURS.items():
        if name not in existing_labels:
            requests.post(
                f"https://api.github.com/repos/{repo}/labels",
                json={"name": name, "color": colour},
                headers=headers,
                timeout=5,
            )


def create_issue(incident: IncidentReport) -> dict:
    settings = get_settings()
    token = settings.github_token
    repo = settings.github_repo

    if not token or not repo:
        print("[GitHub Issues] Credentials not set; returning stub issue.")
        return {
            "issue_number": None,
            "url": "https://github.com/stub",
            "error": "GITHUB_TOKEN or GITHUB_REPO not set",
        }

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }

    try:
        _ensure_labels(repo, headers)
    except Exception:
        pass

    ioc_lines = "\n".join(
        f"- **[{ioc.type}]** `{ioc.value}` - {ioc.reputation or 'unknown reputation'}"
        for ioc in incident.iocs
    ) or "_None identified_"

    mitre_lines = "\n".join(
        f"- [{technique.technique_id}](https://attack.mitre.org/techniques/"
        f"{technique.technique_id.replace('.', '/')}) - "
        f"{technique.technique_name} ({technique.tactic})"
        for technique in incident.mitre_techniques
    ) or "_None mapped_"

    playbook_lines = "\n".join(
        f"{index}. {step}" for index, step in enumerate(incident.playbook_steps, 1)
    ) or "_No steps generated_"

    body = (
        f"## Incident Summary\n{incident.summary or 'N/A'}\n\n"
        "## Classification\n"
        "| Field | Value |\n|---|---|\n"
        f"| Severity | `{incident.severity.value}` |\n"
        f"| Type | {incident.incident_type.value} |\n"
        f"| Confidence | {int(incident.confidence * 100)}% |\n"
        f"| Incident ID | `{incident.id}` |\n\n"
        f"## Indicators of Compromise\n{ioc_lines}\n\n"
        f"## MITRE ATT&CK Techniques\n{mitre_lines}\n\n"
        f"## Recommended Playbook\n{playbook_lines}\n\n"
        "---\n"
        f"_Auto-generated by CSIRT Autopilot "
        f"(Ollama/{settings.ollama_model})_"
    )

    issue_title = f"[{incident.severity.value}] {incident.title or 'Security Incident'}"
    labels = [
        "csirt-autopilot",
        PRIORITY_LABEL.get(incident.severity.value, "priority:medium"),
        incident.incident_type.value,
    ]

    try:
        response = requests.post(
            f"https://api.github.com/repos/{repo}/issues",
            json={"title": issue_title, "body": body, "labels": labels},
            headers=headers,
            timeout=10,
        )
        response.raise_for_status()
        data = response.json()
        print(f"[GitHub Issues] Issue created: #{data['number']} - {data['html_url']}")
        return {
            "issue_number": data["number"],
            "url": data["html_url"],
            "error": None,
        }
    except Exception as exc:
        print(f"[GitHub Issues] Failed: {exc}")
        return {"issue_number": None, "url": None, "error": str(exc)}
